from __future__ import annotations

from typing import Any

import discord


MODE_LABELS = {
    "1v1": "1 vs 1",
    "5v5": "5 vs 5",
}


def enrollment_embed(
    tournament: dict[str, Any],
    participants: list[dict[str, Any]],
) -> discord.Embed:
    status = tournament["status"]
    color = {
        "open": discord.Color.green(),
        "started": discord.Color.blurple(),
        "cancelled": discord.Color.dark_grey(),
    }.get(status, discord.Color.default())

    embed = discord.Embed(
        title=f"7amidelmath Tournament: {tournament['name']}",
        description=(
            "Click **Enroll** to join this tournament. "
            "Click **Withdraw** if you need to leave before it starts."
        ),
        color=color,
    )
    embed.add_field(name="Tournament ID", value=str(tournament["id"]), inline=True)
    embed.add_field(name="Mode", value=MODE_LABELS[tournament["mode"]], inline=True)
    embed.add_field(name="Status", value=status.title(), inline=True)

    max_players = tournament.get("max_players")
    capacity = f"{len(participants)}/{max_players}" if max_players else str(len(participants))
    embed.add_field(name="Enrolled", value=capacity, inline=True)
    if tournament.get("check_in_required"):
        checked_in = sum(1 for participant in participants if participant.get("checked_in"))
        embed.add_field(name="Checked in", value=str(checked_in), inline=True)
    embed.add_field(name="Created by", value=f"<@{tournament['creator_id']}>", inline=True)
    mute_status = "Voice mute on enroll" if tournament.get("mute_on_enroll") else "Off"
    embed.add_field(name="Mute power", value=mute_status, inline=True)

    if tournament.get("game") == "league_of_legends":
        rank_range = _rank_range(tournament)
        embed.add_field(name="Game", value="League of Legends", inline=True)
        embed.add_field(name="Region", value=tournament.get("lol_region") or "Any", inline=True)
        embed.add_field(name="Map", value=tournament.get("lol_map") or "Summoner's Rift", inline=True)
        embed.add_field(name="Ranks", value=rank_range, inline=True)
        if tournament.get("min_account_level"):
            embed.add_field(
                name="Minimum level",
                value=str(tournament["min_account_level"]),
                inline=True,
            )

    if participants:
        players = "\n".join(
            f"{index}. {_participant_line(player, tournament)}"
            for index, player in enumerate(participants[:20], start=1)
        )
        if len(participants) > 20:
            players += f"\n...and {len(participants) - 20} more."
    else:
        players = "Nobody yet. Be the first to enroll."

    embed.add_field(name="Players", value=players, inline=False)
    embed.set_footer(text="Use /tournament start when enrollment is ready.")
    return embed


def bracket_embed(
    tournament: dict[str, Any],
    description: str,
    *,
    page: int = 1,
    total_pages: int = 1,
) -> discord.Embed:
    embed = discord.Embed(
        title=f"Bracket: {tournament['name']}",
        description=description,
        color=discord.Color.gold(),
    )
    embed.add_field(name="Tournament ID", value=str(tournament["id"]), inline=True)
    embed.add_field(name="Mode", value=MODE_LABELS[tournament["mode"]], inline=True)
    if tournament.get("game") == "league_of_legends":
        embed.add_field(name="Game", value="League of Legends", inline=True)
        embed.add_field(name="Region", value=tournament.get("lol_region") or "Any", inline=True)
        embed.add_field(name="Map", value=tournament.get("lol_map") or "Summoner's Rift", inline=True)
    embed.set_footer(text=f"Generated by 7amidelmath | Page {page}/{total_pages}")
    return embed


def bracket_to_text(bracket: dict[str, Any]) -> str:
    if bracket["mode"] == "1v1":
        return _one_vs_one_text(bracket)
    if bracket["mode"] == "5v5":
        return _five_vs_five_text(bracket)
    return "Unsupported bracket mode."


def chunk_text(text: str, *, limit: int = 3800) -> list[str]:
    if len(text) <= limit:
        return [text]

    chunks: list[str] = []
    current = ""
    for line in text.splitlines():
        candidate = f"{current}\n{line}" if current else line
        if len(candidate) > limit:
            chunks.append(current)
            current = line
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks


def _one_vs_one_text(bracket: dict[str, Any]) -> str:
    lines = []
    for round_data in bracket["rounds"]:
        if lines:
            lines.append("")
        lines.append(f"**{round_data['name']}**")
        for match in round_data["matches"]:
            line = (
                f"**Match {match['match_number']}:** "
                f"{_bracket_player(match['player_a'])} vs {_bracket_player(match['player_b'])}"
            )
            if match.get("winner"):
                line += f" - Winner: {_bracket_player(match['winner'])}"
            lines.append(line)

        for player in round_data["byes"]:
            lines.append(f"**Bye:** {_bracket_player(player)} advances automatically.")

    if bracket.get("champion"):
        lines.append("")
        lines.append(f"**Champion:** {_bracket_player(bracket['champion'])}")

    return "\n".join(lines)


def _five_vs_five_text(bracket: dict[str, Any]) -> str:
    round_one = bracket["rounds"][0]
    lines = ["**Teams**"]
    for team in bracket["teams"]:
        average_rank = team.get("average_rank")
        heading = f"**{team['name']}**"
        if average_rank:
            heading += f" - Avg rank: {average_rank}"
        lines.append(heading)
        for player in team["players"]:
            lines.append(f"- {_bracket_player(player)}")

    if bracket["reserves"]:
        reserves = ", ".join(_bracket_player(player) for player in bracket["reserves"])
        lines.append(f"**Reserves:** {reserves}")

    lines.append("")
    lines.append("**Round 1**")
    for match in round_one["matches"]:
        lines.append(
            f"**Match {match['match_number']}:** "
            f"{match['team_a']['name']} vs {match['team_b']['name']}"
        )

    for team in round_one["byes"]:
        lines.append(f"**Bye:** {team['name']} advances automatically.")

    return "\n".join(lines)


def _mention(participant: dict[str, Any]) -> str:
    return f"<@{participant['user_id']}>"


def _participant_line(participant: dict[str, Any], tournament: dict[str, Any]) -> str:
    line = _mention(participant)
    if tournament.get("game") == "league_of_legends":
        profile = _lol_profile_text(participant)
        if profile:
            line += f" - {profile}"
        if tournament.get("check_in_required"):
            line += " - checked in" if participant.get("checked_in") else " - not checked in"
    return line


def _bracket_player(participant: dict[str, Any]) -> str:
    profile = _lol_profile_text(participant)
    if profile:
        return f"{_mention(participant)} ({profile})"
    return _mention(participant)


def _lol_profile_text(participant: dict[str, Any]) -> str:
    riot_name = participant.get("riot_name")
    tag_line = participant.get("tag_line")
    rank = participant.get("rank")
    role = participant.get("preferred_role")
    parts = []
    if riot_name and tag_line:
        parts.append(f"{riot_name}#{tag_line}")
    if rank:
        parts.append(rank)
    if role:
        parts.append(role)
    return ", ".join(parts)


def _rank_range(tournament: dict[str, Any]) -> str:
    rank_min = tournament.get("rank_min")
    rank_max = tournament.get("rank_max")
    if rank_min and rank_max:
        return f"{rank_min} to {rank_max}"
    if rank_min:
        return f"{rank_min}+"
    if rank_max:
        return f"Up to {rank_max}"
    return "Any"
