from __future__ import annotations

from typing import Any

import discord


MODE_LABELS = {
    "1v1": "1 vs 1",
    "5v5": "5 vs 5",
}


def enrollment_embed(
    tournament: dict[str, Any],
    participants: list[dict[str, Any]],
) -> discord.Embed:
    status = tournament["status"]
    color = {
        "open": discord.Color.green(),
        "started": discord.Color.blurple(),
        "cancelled": discord.Color.dark_grey(),
    }.get(status, discord.Color.default())

    embed = discord.Embed(
        title=f"7amidelmath Tournament: {tournament['name']}",
        description=(
            "Click **Enroll** to join this tournament. "
            "Click **Withdraw** if you need to leave before it starts."
        ),
        color=color,
    )
    embed.add_field(name="Tournament ID", value=str(tournament["id"]), inline=True)
    embed.add_field(name="Mode", value=MODE_LABELS[tournament["mode"]], inline=True)
    embed.add_field(name="Status", value=status.title(), inline=True)

    max_players = tournament.get("max_players")
    capacity = f"{len(participants)}/{max_players}" if max_players else str(len(participants))
    embed.add_field(name="Enrolled", value=capacity, inline=True)
    embed.add_field(name="Created by", value=f"<@{tournament['creator_id']}>", inline=True)
    mute_status = "Voice mute on enroll" if tournament.get("mute_on_enroll") else "Off"
    embed.add_field(name="Mute power", value=mute_status, inline=True)

    if participants:
        players = "\n".join(
            f"{index}. {_mention(player)}"
            for index, player in enumerate(participants[:20], start=1)
        )
        if len(participants) > 20:
            players += f"\n...and {len(participants) - 20} more."
    else:
        players = "Nobody yet. Be the first to enroll."

    embed.add_field(name="Players", value=players, inline=False)
    embed.set_footer(text="Use /tournament start when enrollment is ready.")
    return embed


def bracket_embed(
    tournament: dict[str, Any],
    description: str,
    *,
    page: int = 1,
    total_pages: int = 1,
) -> discord.Embed:
    embed = discord.Embed(
        title=f"Bracket: {tournament['name']}",
        description=description,
        color=discord.Color.gold(),
    )
    embed.add_field(name="Tournament ID", value=str(tournament["id"]), inline=True)
    embed.add_field(name="Mode", value=MODE_LABELS[tournament["mode"]], inline=True)
    embed.set_footer(text=f"Generated by 7amidelmath | Page {page}/{total_pages}")
    return embed


def bracket_to_text(bracket: dict[str, Any]) -> str:
    if bracket["mode"] == "1v1":
        return _one_vs_one_text(bracket)
    if bracket["mode"] == "5v5":
        return _five_vs_five_text(bracket)
    return "Unsupported bracket mode."


def chunk_text(text: str, *, limit: int = 3800) -> list[str]:
    if len(text) <= limit:
        return [text]

    chunks: list[str] = []
    current = ""
    for line in text.splitlines():
        candidate = f"{current}\n{line}" if current else line
        if len(candidate) > limit:
            chunks.append(current)
            current = line
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks


def _one_vs_one_text(bracket: dict[str, Any]) -> str:
    round_one = bracket["rounds"][0]
    lines = ["**Round 1**"]
    for match in round_one["matches"]:
        lines.append(
            f"**Match {match['match_number']}:** "
            f"{_mention(match['player_a'])} vs {_mention(match['player_b'])}"
        )

    for player in round_one["byes"]:
        lines.append(f"**Bye:** {_mention(player)} advances automatically.")

    return "\n".join(lines)


def _five_vs_five_text(bracket: dict[str, Any]) -> str:
    round_one = bracket["rounds"][0]
    lines = ["**Teams**"]
    for team in bracket["teams"]:
        players = ", ".join(_mention(player) for player in team["players"])
        lines.append(f"**{team['name']}:** {players}")

    if bracket["reserves"]:
        reserves = ", ".join(_mention(player) for player in bracket["reserves"])
        lines.append(f"**Reserves:** {reserves}")

    lines.append("")
    lines.append("**Round 1**")
    for match in round_one["matches"]:
        lines.append(
            f"**Match {match['match_number']}:** "
            f"{match['team_a']['name']} vs {match['team_b']['name']}"
        )

    for team in round_one["byes"]:
        lines.append(f"**Bye:** {team['name']} advances automatically.")

    return "\n".join(lines)


def _mention(participant: dict[str, Any]) -> str:
    return f"<@{participant['user_id']}>"
